name: Build all containers on Ubuntu

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Docker login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Set up Docker buildx
          id: buildx
          uses: docker/setup-buildx-action@master

        - name: Cache docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: ${{ runner.os}}-buildx-

        - name: Build and push minimal
          uses: docker/build-push-action@v2
          id: docker_build_minimal
          with:
            context: ubuntu-minimal
            file: ubuntu-minimal/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: nrandell/openvino-minimal:latest
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache

        - name: Minimal image digest
          run: echo ${{ steps.docker_build_minimal.outputs.digest }}

        - name: Build and push dotnet minimal
          uses: docker/build-push-action@v2
          id: docker_build_dotnet
          with:
            context: dotnet
            file: dotnet/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: nrandell/dotnet-openvino:latest
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache

        - name: Dotnet image digest
          run: echo ${{ steps.docker_build_dotnet.outputs.digest }}

        - name: Build and push full
          uses: docker/build-push-action@v2
          id: docker_build_full
          with:
            context: ubuntu
            file: ubuntu/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: nrandell/openvino:latest
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache

        - name: Full image digest
          run: echo ${{ steps.docker_build_full.outputs.digest }}

        - name: Build ubuntu nuget package
          uses: docker/build-push-action@v2
          id: docker_build_nuget
          with:
            context: ubuntu
            file: ubuntu/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: false
            tags: nrandell/openvino-nuget:latest
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            build-args: NUGET_KEY=${{ secrets.NUGET_KEY }}

        - name: Full image digest
          run: echo ${{ steps.docker_build_full.outputs.digest }}



